<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net8.0-windows;net6.0-windows</TargetFrameworks>
    <LangVersion>12</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="native-entry/**/*.cs" />
    <ProjectReference Include="../server/src/managed/Nanaimo.Gameplay.csproj" />
    <None Update="Start-Server.ps1" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
