# Inventory administration UI for the Korean Nanaimo launcher.
# Dot-source this file, then call Initialize-InventoryAdmin and Save-InventoryAdminState.

function Invoke-InventoryAdminPython([string[]]$Arguments) {
    $root=Split-Path $PSScriptRoot -Parent
    $bundled=Join-Path $root 'tools\python\python.exe'
    $py=if(Test-Path -LiteralPath $bundled){$bundled}else{(Get-Command python -ErrorAction Stop).Source}
    $output=& $py -B @Arguments 2>&1
    if($LASTEXITCODE-ne0){throw (($output|Out-String).Trim())}
    return ($output|Out-String).Trim()
}
function New-InventoryAdminGrid($parent,[int]$x,[int]$y,[int]$w,[int]$h){
    $g=New-Object Windows.Forms.DataGridView;$g.Location=New-Object Drawing.Point($x,$y);$g.Size=New-Object Drawing.Size($w,$h);$g.ReadOnly=$true;$g.AllowUserToAddRows=$false;$g.AllowUserToDeleteRows=$false;$g.MultiSelect=$false;$g.SelectionMode='FullRowSelect';$g.AutoSizeColumnsMode='DisplayedCells';$g.RowHeadersVisible=$false;$parent.Controls.Add($g);return $g
}
function New-InventoryAdminTable([string[]]$Columns){$t=New-Object Data.DataTable;$t.TableName='T'+[guid]::NewGuid().ToString('N');foreach($c in $Columns){[void]$t.Columns.Add($c)};return ,$t}
function Escape-InventoryAdminFilter([string]$s){return $s.Replace("'","''").Replace('[','[[]').Replace('%','[%]').Replace('*','[*]')}
function Set-InventoryAdminFilter($view,[string]$q,[string[]]$columns){$q=Escape-InventoryAdminFilter $q.Trim();if(-not$q){$view.RowFilter='';return};$view.RowFilter=(($columns|ForEach-Object{"[$_] LIKE '%$q%'"})-join' OR ')}
function Get-InventoryAdminCode($grid){if(-not$grid.CurrentRow){return 0};try{return [uint32]$grid.CurrentRow.Cells['ID'].Value}catch{return 0}}
function Write-InventoryAdminTempJson($value){$p=Join-Path ([IO.Path]::GetTempPath()) ('nanaimo-inventory-'+[guid]::NewGuid().ToString('N')+'.json');[IO.File]::WriteAllText($p,($value|ConvertTo-Json -Depth 8 -Compress),(New-Object Text.UTF8Encoding($false)));return $p}

function Initialize-InventoryAdmin($Tabs,[string]$Root,[string]$NameHex){
    $backend=Join-Path $Root 'gui_launcher\inventory_admin_backend.py';if(-not(Test-Path -LiteralPath $backend)){throw 'The end of the item management does not exist。'}
    $dataDir=Join-Path $Root 'gui_launcher\data';$needed='inventory_clothing.json','inventory_pets.json','inventory_pet_gems.json','inventory_game_items.json','inventory_furniture.json','inventory_cards.json';foreach($n in $needed){if(-not(Test-Path -LiteralPath (Join-Path $dataDir $n))){throw "Missing Object Directory: $n"}}
    $tmp=Join-Path ([IO.Path]::GetTempPath()) ('nanaimo-snapshot-'+[guid]::NewGuid().ToString('N')+'.json')
    try{[void](Invoke-InventoryAdminPython @($backend,'snapshot','--root',$Root,'--name-hex',$NameHex,'--output',$tmp));$snap=Get-Content -LiteralPath $tmp -Raw -Encoding UTF8|ConvertFrom-Json}finally{Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue}
    $catalog=@{clothing=Get-Content -LiteralPath (Join-Path $dataDir 'inventory_clothing.json') -Raw -Encoding UTF8|ConvertFrom-Json;pets=Get-Content -LiteralPath (Join-Path $dataDir 'inventory_pets.json') -Raw -Encoding UTF8|ConvertFrom-Json;gems=Get-Content -LiteralPath (Join-Path $dataDir 'inventory_pet_gems.json') -Raw -Encoding UTF8|ConvertFrom-Json;game=Get-Content -LiteralPath (Join-Path $dataDir 'inventory_game_items.json') -Raw -Encoding UTF8|ConvertFrom-Json;furniture=Get-Content -LiteralPath (Join-Path $dataDir 'inventory_furniture.json') -Raw -Encoding UTF8|ConvertFrom-Json;cards=Get-Content -LiteralPath (Join-Path $dataDir 'inventory_cards.json') -Raw -Encoding UTF8|ConvertFrom-Json}
    $ctx=[pscustomobject]@{Root=$Root;Backend=$backend;AccountSuffix=[string]$snap.account_suffix;Catalog=$catalog;Clothing=New-Object Collections.ArrayList;Pets=New-Object Collections.ArrayList;GameItems=New-Object Collections.ArrayList;Furniture=New-Object Collections.ArrayList;Cards=New-Object Collections.ArrayList;Shop=$snap.shop;RefreshAll=$null}
    foreach($x in $snap.clothing){[void]$ctx.Clothing.Add([uint32]$x)};foreach($x in $snap.pets){[void]$ctx.Pets.Add([pscustomobject]@{code=[uint32]$x.code;upgrade_material=[uint32]$x.upgrade_material;gems=@([uint32]$x.gems[0],[uint32]$x.gems[1],[uint32]$x.gems[2])})};foreach($x in $snap.game_items){[void]$ctx.GameItems.Add([pscustomobject]@{code=[uint32]$x.code;count=[uint32]$x.count;carrier=[string]$x.carrier})};foreach($x in $snap.furniture){[void]$ctx.Furniture.Add([pscustomobject]@{code=[uint32]$x.code;index=[uint16]$x.index;placed=[bool]$x.placed;type=[byte]$x.type;x=[int16]$x.x;y=[int16]$x.y;z=[byte]$x.z;mirror=[byte]$x.mirror})};foreach($x in $snap.cards){[void]$ctx.Cards.Add([pscustomobject]@{code=[uint32]$x.code;count=[uint32]$x.count})}
    $byCloth=@{};foreach($x in $catalog.clothing){$byCloth[[uint32]$x.id]=$x};$byPet=@{};foreach($x in $catalog.pets){$byPet[[uint32]$x.id]=$x};$byGem=@{};foreach($x in $catalog.gems){$byGem[[uint32]$x.id]=$x};$byGame=@{};foreach($x in $catalog.game){$byGame[[uint32]$x.id]=$x};$byFurniture=@{};foreach($x in $catalog.furniture){$byFurniture[[uint32]$x.id]=$x};$byCard=@{};foreach($x in $catalog.cards){$byCard[[uint32]$x.id]=$x}

    # Clothing box
    $tab=New-Object Windows.Forms.TabPage;$tab.Text='Garment management';$Tabs.TabPages.Add($tab);$ownedSearch=New-Object Windows.Forms.TextBox;$ownedSearch.Location='15,15';$ownedSearch.Size='350,26';$tab.Controls.Add($ownedSearch);$allSearch=New-Object Windows.Forms.TextBox;$allSearch.Location='555,15';$allSearch.Size='350,26';$tab.Controls.Add($allSearch)
    $ownedGrid=New-InventoryAdminGrid $tab 15 50 430 650;$allGrid=New-InventoryAdminGrid $tab 555 50 525 650
    $ot=New-InventoryAdminTable @('Name','ID','Parts','Gender');$ov=New-Object Data.DataView;$ov.Table=$ot;$ownedGrid.DataSource=$ov;$at=New-InventoryAdminTable @('Name','ID','Parts','Gender','Impact statement');foreach($x in $catalog.clothing){[void]$at.Rows.Add($x.name,[string]$x.id,$x.part,$x.gender,$x.effect_description)};$av=New-Object Data.DataView;$av.Table=$at;$allGrid.DataSource=$av
    $refreshClothing={ $ot.Rows.Clear();foreach($code in $ctx.Clothing){$x=$byCloth[[uint32]$code];if($x){[void]$ot.Rows.Add($x.name,[string]$x.id,$x.part,$x.gender)}} }.GetNewClosure();&$refreshClothing
    $add=New-Object Windows.Forms.Button;$add.Text='← Add';$add.Location='460,260';$add.Size='80,35';$tab.Controls.Add($add);$del=New-Object Windows.Forms.Button;$del.Text='Delete →';$del.Location='460,310';$del.Size='80,35';$tab.Controls.Add($del)
    $ownedSearch.add_TextChanged(({Set-InventoryAdminFilter $ov $ownedSearch.Text @('Name','ID','Parts','Gender')}).GetNewClosure());$allSearch.add_TextChanged(({Set-InventoryAdminFilter $av $allSearch.Text @('Name','ID','Parts','Gender','Impact statement')}).GetNewClosure())
    $add.add_Click(({ $c=Get-InventoryAdminCode $allGrid;if($c-and-not($ctx.Clothing-contains$c)){if($ctx.Clothing.Count-ge256){[Windows.Forms.MessageBox]::Show('The maximum limit for the suitcase is256Seed。')|Out-Null;return};[void]$ctx.Clothing.Add($c);&$refreshClothing}}).GetNewClosure());$del.add_Click(({ $c=Get-InventoryAdminCode $ownedGrid;if($c){[void]$ctx.Clothing.Remove($c);&$refreshClothing}}).GetNewClosure());$allGrid.add_CellDoubleClick(({param($s,$e)$add.PerformClick()}).GetNewClosure())

    # Pet box + gems/attributes
    $petTab=New-Object Windows.Forms.TabPage;$petTab.Text='Pet Box Management';$Tabs.TabPages.Add($petTab)
    $ph1=New-Object Windows.Forms.Label;$ph1.Text='① Existing pets: Select the pets to view or edit first';$ph1.Location='10,6';$ph1.Size='340,22';$ph1.Font=New-Object Drawing.Font('Microsoft YaHei UI',9,[Drawing.FontStyle]::Bold);$petTab.Controls.Add($ph1)
    $ph2=New-Object Windows.Forms.Label;$ph2.Text='② Full pets: After filtering, add left pet box';$ph2.Location='375,6';$ph2.Size='340,22';$ph2.Font=New-Object Drawing.Font('Microsoft YaHei UI',9,[Drawing.FontStyle]::Bold);$petTab.Controls.Add($ph2)
    $ph3=New-Object Windows.Forms.Label;$ph3.Text='③ Full gemstone: Load left pet after selection';$ph3.Location='740,6';$ph3.Size='340,22';$ph3.Font=New-Object Drawing.Font('Microsoft YaHei UI',9,[Drawing.FontStyle]::Bold);$petTab.Controls.Add($ph3)
    $ps1=New-Object Windows.Forms.TextBox;$ps1.Location='10,30';$ps1.Size='280,25';$petTab.Controls.Add($ps1);$ps2=New-Object Windows.Forms.TextBox;$ps2.Location='375,30';$ps2.Size='280,25';$petTab.Controls.Add($ps2);$gs=New-Object Windows.Forms.TextBox;$gs.Location='740,30';$gs.Size='280,25';$petTab.Controls.Add($gs)
    $pg1=New-InventoryAdminGrid $petTab 10 62 340 463;$pg2=New-InventoryAdminGrid $petTab 375 62 340 463;$gg=New-InventoryAdminGrid $petTab 740 62 340 463
    $pt1=New-InventoryAdminTable @('Name','ID','Base attack','Effective attack','HPAdd','MPAdd','Slot','Gems1','Gems2','Gems3');$pv1=New-Object Data.DataView;$pv1.Table=$pt1;$pg1.DataSource=$pv1;$pt2=New-InventoryAdminTable @('Name','ID','Base attack','Slot','Level Requirements');foreach($x in $catalog.pets){[void]$pt2.Rows.Add($x.name,[string]$x.id,[string]$x.base_attack,[string]$x.slot_count,[string]$x.level_requirement)};$pv2=New-Object Data.DataView;$pv2.Table=$pt2;$pg2.DataSource=$pv2;$gt=New-InventoryAdminTable @('Name','ID','Effects','Attack','Attack%','HP','MP');foreach($x in $catalog.gems){[void]$gt.Rows.Add($x.name,[string]$x.id,$x.effect,[string]$x.attack_flat,[string]$x.attack_percent,[string]$x.hp,[string]$x.mp)};$gv=New-Object Data.DataView;$gv.Table=$gt;$gg.DataSource=$gv
    $petDetail=New-Object Windows.Forms.Label;$petDetail.Location='15,615';$petDetail.Size='1040,45';$petDetail.Font=New-Object Drawing.Font('Microsoft YaHei UI',10);$petTab.Controls.Add($petDetail)
    $refreshPets={ $selected=Get-InventoryAdminCode $pg1;$pt1.Rows.Clear();foreach($r in $ctx.Pets){$p=$byPet[[uint32]$r.code];if(-not$p){continue};$flat=0;$pct=0;$hp=0;$mp=0;$names=@();foreach($g in $r.gems){$d=$byGem[[uint32]$g];if($d){$flat+=[int]$d.attack_flat;$pct+=[int]$d.attack_percent;$hp+=[int]$d.hp;$mp+=[int]$d.mp;$names+=$d.name}else{$names+='-'}};$base=[int]$p.base_attack;$eff=$base+$flat+[math]::Floor($base*$pct/100);[void]$pt1.Rows.Add($p.name,[string]$p.id,[string]$base,[string]$eff,[string]$hp,[string]$mp,[string]$p.slot_count,$names[0],$names[1],$names[2])};if($selected){foreach($row in $pg1.Rows){if([uint32]$row.Cells['ID'].Value-eq$selected){$row.Selected=$true;$pg1.CurrentCell=$row.Cells[0];break}}} }.GetNewClosure();&$refreshPets
    $petAdd=New-Object Windows.Forms.Button;$petAdd.Text='Add the middle pet to the left column';$petAdd.Location='375,535';$petAdd.Size='200,34';$petTab.Controls.Add($petAdd);$petDel=New-Object Windows.Forms.Button;$petDel.Text='Remove left row selected pet';$petDel.Location='15,535';$petDel.Size='210,34';$petDel.BackColor=[Drawing.Color]::MistyRose;$petTab.Controls.Add($petDel);$upgrade=New-Object Windows.Forms.CheckBox;$upgrade.Text='Gold powder upgrade';$upgrade.Location='15,578';$upgrade.Size='130,28';$petTab.Controls.Add($upgrade)
    $slotButtons=@();for($i=0;$i-lt3;$i++){$b=New-Object Windows.Forms.Button;$b.Text="Load Slot$($i+1)";$b.Location=New-Object Drawing.Point((740+$i*110),535);$b.Size='103,34';$petTab.Controls.Add($b);$slotButtons+=$b};$clearGem=New-Object Windows.Forms.Button;$clearGem.Text='Empty the specified slot';$clearGem.Location='740,575';$clearGem.Size='110,32';$petTab.Controls.Add($clearGem);$slotPick=New-Object Windows.Forms.NumericUpDown;$slotPick.Minimum=1;$slotPick.Maximum=3;$slotPick.Value=1;$slotPick.Location='860,578';$slotPick.Size='55,28';$petTab.Controls.Add($slotPick);$slotHint=New-Object Windows.Forms.Label;$slotHint.Text='Slot';$slotHint.Location='920,581';$slotHint.Size='45,25';$petTab.Controls.Add($slotHint);$petHelp=New-Object Windows.Forms.Label;$petHelp.Text='Delete: Left Column Select pet → Point red button below the left column. Fill with stones: left column selected pet → Right-Booked Jewels → Dot Load Slot1/2/3。';$petHelp.Location='15,665';$petHelp.Size='1040,30';$petHelp.ForeColor=[Drawing.Color]::DarkBlue;$petTab.Controls.Add($petHelp)
    $getPetRow={param([uint32]$code)return @($ctx.Pets|Where-Object{[uint32]$_.code-eq$code})[0]}.GetNewClosure()
    $updatePetDetail={ $c=Get-InventoryAdminCode $pg1;if(-not$c){$petDetail.Text='Select the existing pet to view the properties and edit the gems。';return};$r=&$getPetRow $c;$p=$byPet[$c];$upgrade.Checked=([uint32]$r.upgrade_material-ne0);$petDetail.Text="$($p.name) [$c]  Base attack=$($p.base_attack)，Slot=$($p.slot_count)，Age Dollardata=$($p.display_age)/$($p.max_age)，Level Requirements=$($p.level_requirement)，Upgrade material=$($p.upgrade_material)" }.GetNewClosure();$pg1.add_SelectionChanged($updatePetDetail);&$updatePetDetail
    $ps1.add_TextChanged(({Set-InventoryAdminFilter $pv1 $ps1.Text @('Name','ID','Gems1','Gems2','Gems3')}).GetNewClosure());$ps2.add_TextChanged(({Set-InventoryAdminFilter $pv2 $ps2.Text @('Name','ID','Base attack','Level Requirements')}).GetNewClosure());$gs.add_TextChanged(({Set-InventoryAdminFilter $gv $gs.Text @('Name','ID','Effects','Attack','Attack%','HP','MP')}).GetNewClosure())
    $petAdd.add_Click(({ $c=Get-InventoryAdminCode $pg2;if(-not$c-or@($ctx.Pets|Where-Object{$_.code-eq$c}).Count){return};if($ctx.Pets.Count-ge128){[Windows.Forms.MessageBox]::Show('The ceiling for pet boxes is128Only；clientCurrent maximum at a time56Okay, the selected pet will be kept in visible rows。')|Out-Null;return};[void]$ctx.Pets.Add([pscustomobject]@{code=$c;upgrade_material=0;gems=@(0,0,0)});&$refreshPets}).GetNewClosure());$petDel.add_Click(({ $c=Get-InventoryAdminCode $pg1;if($c){$r=&$getPetRow $c;if($r){[void]$ctx.Pets.Remove($r);&$refreshPets}}}).GetNewClosure())
    for($i=0;$i-lt3;$i++){$slot=$i;$slotButtons[$i].add_Click(({ $pc=Get-InventoryAdminCode $pg1;$gc=Get-InventoryAdminCode $gg;if(-not$pc-or-not$gc){return};$r=&$getPetRow $pc;$p=$byPet[$pc];if($slot-ge[int]$p.slot_count){[Windows.Forms.MessageBox]::Show("Theres only one pet $($p.slot_count) A squirt。")|Out-Null;return};$r.gems[$slot]=$gc;&$refreshPets;&$updatePetDetail}).GetNewClosure())}
    $clearGem.add_Click(({ $pc=Get-InventoryAdminCode $pg1;if(-not$pc){return};$r=&$getPetRow $pc;$r.gems[[int]$slotPick.Value-1]=0;&$refreshPets;&$updatePetDetail}).GetNewClosure());$upgrade.add_CheckedChanged(({ $pc=Get-InventoryAdminCode $pg1;if(-not$pc){return};$r=&$getPetRow $pc;$p=$byPet[$pc];$r.upgrade_material=if($upgrade.Checked){[uint32]$p.upgrade_material}else{0}}).GetNewClosure())

    # Game items
    $gameTab=New-Object Windows.Forms.TabPage;$gameTab.Text='Game prop management';$Tabs.TabPages.Add($gameTab);$gos=New-Object Windows.Forms.TextBox;$gos.Location='15,15';$gos.Size='350,26';$gameTab.Controls.Add($gos);$gas=New-Object Windows.Forms.TextBox;$gas.Location='555,15';$gas.Size='350,26';$gameTab.Controls.Add($gas);$gog=New-InventoryAdminGrid $gameTab 15 50 430 650;$gag=New-InventoryAdminGrid $gameTab 555 50 525 650
    $got=New-InventoryAdminTable @('Name','ID','Number','Carrier','Classification');$gov=New-Object Data.DataView;$gov.Table=$got;$gog.DataSource=$gov;$gat=New-InventoryAdminTable @('Name','ID','Carrier','Classification','Annotations','Effects');foreach($x in $catalog.game){[void]$gat.Rows.Add($x.name,[string]$x.id,$x.carrier,$x.category,$x.description,$x.effect)};$gav=New-Object Data.DataView;$gav.Table=$gat;$gag.DataSource=$gav
    $refreshGame={ $got.Rows.Clear();foreach($r in $ctx.GameItems){$x=$byGame[[uint32]$r.code];[void]$got.Rows.Add($(if($x){$x.name}else{"ITEM-$($r.code)"}),[string]$r.code,[string]$r.count,$r.carrier,$(if($x){$x.category}else{''}))} }.GetNewClosure();&$refreshGame
    $qty=New-Object Windows.Forms.NumericUpDown;$qty.Minimum=1;$qty.Maximum=255;$qty.Value=1;$qty.Location='465,235';$qty.Size='75,28';$gameTab.Controls.Add($qty);$ga=New-Object Windows.Forms.Button;$ga.Text='← Increase';$ga.Location='460,275';$ga.Size='80,34';$gameTab.Controls.Add($ga);$gd=New-Object Windows.Forms.Button;$gd.Text='Reduction/Delete →';$gd.Location='450,325';$gd.Size='95,34';$gameTab.Controls.Add($gd)
    $gos.add_TextChanged(({Set-InventoryAdminFilter $gov $gos.Text @('Name','ID','Carrier','Classification')}).GetNewClosure());$gas.add_TextChanged(({Set-InventoryAdminFilter $gav $gas.Text @('Name','ID','Carrier','Classification','Annotations','Effects')}).GetNewClosure())
    $ga.add_Click(({ $c=Get-InventoryAdminCode $gag;if(-not$c){return};$carrier=[string]$gag.CurrentRow.Cells['Carrier'].Value;$r=@($ctx.GameItems|Where-Object{$_.code-eq$c-and$_.carrier-eq$carrier})[0];if($r){$r.count=[math]::Min(255,[int]$r.count+[int]$qty.Value)}else{[void]$ctx.GameItems.Add([pscustomobject]@{code=$c;count=[uint32]$qty.Value;carrier=$carrier})};&$refreshGame}).GetNewClosure());$gd.add_Click(({ $c=Get-InventoryAdminCode $gog;if(-not$c){return};$carrier=[string]$gog.CurrentRow.Cells['Carrier'].Value;$r=@($ctx.GameItems|Where-Object{$_.code-eq$c-and$_.carrier-eq$carrier})[0];if($r){$r.count=[int]$r.count-[int]$qty.Value;if($r.count-le0){[void]$ctx.GameItems.Remove($r)};&$refreshGame}}).GetNewClosure())

    # Furniture
    $fTab=New-Object Windows.Forms.TabPage;$fTab.Text='Decorative Furniture Management';$Tabs.TabPages.Add($fTab);$fos=New-Object Windows.Forms.TextBox;$fos.Location='15,15';$fos.Size='350,26';$fTab.Controls.Add($fos);$fas=New-Object Windows.Forms.TextBox;$fas.Location='555,15';$fas.Size='350,26';$fTab.Controls.Add($fas);$fog=New-InventoryAdminGrid $fTab 15 50 430 650;$fag=New-InventoryAdminGrid $fTab 555 50 525 650
    $fot=New-InventoryAdminTable @('Name','ID','Examples','Type','Its set','X','Y');$fov=New-Object Data.DataView;$fov.Table=$fot;$fog.DataSource=$fov;$fat=New-InventoryAdminTable @('Name','ID','Type','Duration','Gold','NANA','Annotations');foreach($x in $catalog.furniture){[void]$fat.Rows.Add($x.name,[string]$x.id,$x.type_name,[string]$x.days,[string]$x.coin,[string]$x.nana,$x.description)};$fav=New-Object Data.DataView;$fav.Table=$fat;$fag.DataSource=$fav
    $refreshFurniture={ $fot.Rows.Clear();foreach($r in $ctx.Furniture){$x=$byFurniture[[uint32]$r.code];[void]$fot.Rows.Add($(if($x){$x.name}else{"FURNITURE-$($r.code)"}),[string]$r.code,[string]$r.index,$(if($x){$x.type_name}else{$r.type}),$(if($r.placed){'Yes'}else{'No'}),[string]$r.x,[string]$r.y)} }.GetNewClosure();&$refreshFurniture
    $fa=New-Object Windows.Forms.Button;$fa.Text='← Add instance';$fa.Location='450,275';$fa.Size='95,35';$fTab.Controls.Add($fa);$fd=New-Object Windows.Forms.Button;$fd.Text='Remove instance →';$fd.Location='450,325';$fd.Size='95,35';$fTab.Controls.Add($fd);$fos.add_TextChanged(({Set-InventoryAdminFilter $fov $fos.Text @('Name','ID','Examples','Type','Its set')}).GetNewClosure());$fas.add_TextChanged(({Set-InventoryAdminFilter $fav $fas.Text @('Name','ID','Type','Annotations')}).GetNewClosure())
    $fa.add_Click(({ $c=Get-InventoryAdminCode $fag;if(-not$c){return};if($ctx.Furniture.Count-ge254){[Windows.Forms.MessageBox]::Show('The ceiling for the furniture instance is254。')|Out-Null;return};$used=@($ctx.Furniture|ForEach-Object{[int]$_.index});$idx=1;while($used-contains$idx){$idx++};$x=$byFurniture[$c];[void]$ctx.Furniture.Add([pscustomobject]@{code=$c;index=$idx;placed=$false;type=[byte]$x.type;x=400;y=300;z=0;mirror=0});&$refreshFurniture}).GetNewClosure());$fd.add_Click(({ if(-not$fog.CurrentRow){return};$idx=[int]$fog.CurrentRow.Cells['Examples'].Value;$r=@($ctx.Furniture|Where-Object{$_.index-eq$idx})[0];if($r){[void]$ctx.Furniture.Remove($r);&$refreshFurniture}}).GetNewClosure())

    # Cards
    $cTab=New-Object Windows.Forms.TabPage;$cTab.Text='Card Management';$Tabs.TabPages.Add($cTab);$cos=New-Object Windows.Forms.TextBox;$cos.Location='15,15';$cos.Size='350,26';$cTab.Controls.Add($cos);$cas=New-Object Windows.Forms.TextBox;$cas.Location='555,15';$cas.Size='350,26';$cTab.Controls.Add($cas);$cog=New-InventoryAdminGrid $cTab 15 50 430 650;$cag=New-InventoryAdminGrid $cTab 555 50 525 650
    $cot=New-InventoryAdminTable @('Name','ID','Number');$cov=New-Object Data.DataView;$cov.Table=$cot;$cog.DataSource=$cov;$cat=New-InventoryAdminTable @('Name','ID','Annotations','Effects','Products');foreach($x in $catalog.cards){[void]$cat.Rows.Add($x.name,[string]$x.id,$x.description,$x.effect,$x.result)};$cav=New-Object Data.DataView;$cav.Table=$cat;$cag.DataSource=$cav
    $refreshCards={ $cot.Rows.Clear();foreach($r in $ctx.Cards){$x=$byCard[[uint32]$r.code];[void]$cot.Rows.Add($(if($x){$x.name}else{"CARD-$($r.code)"}),[string]$r.code,[string]$r.count)} }.GetNewClosure();&$refreshCards
    $cqty=New-Object Windows.Forms.NumericUpDown;$cqty.Minimum=1;$cqty.Maximum=255;$cqty.Value=1;$cqty.Location='465,235';$cqty.Size='75,28';$cTab.Controls.Add($cqty);$ca=New-Object Windows.Forms.Button;$ca.Text='← Increase';$ca.Location='460,275';$ca.Size='80,34';$cTab.Controls.Add($ca);$cd=New-Object Windows.Forms.Button;$cd.Text='Reduction/Delete →';$cd.Location='450,325';$cd.Size='95,34';$cTab.Controls.Add($cd);$cos.add_TextChanged(({Set-InventoryAdminFilter $cov $cos.Text @('Name','ID')}).GetNewClosure());$cas.add_TextChanged(({Set-InventoryAdminFilter $cav $cas.Text @('Name','ID','Annotations','Effects','Products')}).GetNewClosure())
    $ca.add_Click(({ $c=Get-InventoryAdminCode $cag;if(-not$c){return};$r=@($ctx.Cards|Where-Object{$_.code-eq$c})[0];if($r){$r.count=[math]::Min(255,[int]$r.count+[int]$cqty.Value)}else{[void]$ctx.Cards.Add([pscustomobject]@{code=$c;count=[uint32]$cqty.Value})};&$refreshCards}).GetNewClosure());$cd.add_Click(({ $c=Get-InventoryAdminCode $cog;if(-not$c){return};$r=@($ctx.Cards|Where-Object{$_.code-eq$c})[0];if($r){$r.count=[int]$r.count-[int]$cqty.Value;if($r.count-le0){[void]$ctx.Cards.Remove($r)};&$refreshCards}}).GetNewClosure())
    $ctx.RefreshAll={&$refreshClothing;&$refreshPets;&$refreshGame;&$refreshFurniture;&$refreshCards}.GetNewClosure()
    return $ctx
}

function Save-InventoryAdminState($Context,[string]$NameHex,$Shop){
    $state=[ordered]@{version=1;shop=$Shop;clothing=@($Context.Clothing);pets=@($Context.Pets|ForEach-Object{[ordered]@{code=[uint32]$_.code;upgrade_material=[uint32]$_.upgrade_material;gems=@([uint32]$_.gems[0],[uint32]$_.gems[1],[uint32]$_.gems[2])}});game_items=@($Context.GameItems|ForEach-Object{[ordered]@{code=[uint32]$_.code;count=[uint32]$_.count;carrier=[string]$_.carrier}});furniture=@($Context.Furniture);cards=@($Context.Cards|ForEach-Object{[ordered]@{code=[uint32]$_.code;count=[uint32]$_.count}})}
    $tmp=Write-InventoryAdminTempJson $state
    try{$out=Invoke-InventoryAdminPython @($Context.Backend,'apply','--root',$Context.Root,'--name-hex',$NameHex,'--input',$tmp);return ($out|ConvertFrom-Json)}finally{Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue}
}

function Test-InventoryAdminInstallation([string]$Root){
    $backend=Join-Path $Root 'gui_launcher\inventory_admin_backend.py';$summary=Get-Content -LiteralPath (Join-Path $Root 'gui_launcher\data\inventory_catalog_summary.json') -Raw -Encoding UTF8|ConvertFrom-Json
    if([int]$summary.counts.'inventory_clothing.json'-ne3885-or[int]$summary.counts.'inventory_pets.json'-ne868-or[int]$summary.counts.'inventory_pet_gems.json'-ne18931-or[int]$summary.counts.'inventory_furniture.json'-ne781-or[int]$summary.counts.'inventory_cards.json'-ne420){throw 'The catalogue of items failed to verify。'}
    return Invoke-InventoryAdminPython @($backend,'selftest','--root',$Root)
}
